# Generated by Django 3.1.1 on 2020-09-08 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchemaColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "column_type",
                    models.CharField(
                        choices=[
                            ("fullname", "fullname"),
                            ("job", "job"),
                            ("email", "email"),
                            ("domain", "domain"),
                            ("phone", "phone"),
                            ("company", "company"),
                            ("integer", "integer"),
                            ("address", "address"),
                            ("date", "date"),
                        ],
                        default="fullname",
                        max_length=12,
                    ),
                ),
                ("int_min", models.SmallIntegerField(default=0)),
                ("int_max", models.SmallIntegerField(default=0)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field_delimiter",
                    models.CharField(
                        choices=[
                            (",", "comma"),
                            (";", "semicolon"),
                            (":", "colon"),
                            ("{Tab}", "tab"),
                            ("{space}", "space"),
                        ],
                        default=",",
                        max_length=10,
                    ),
                ),
                (
                    "string_delimiter",
                    models.CharField(
                        choices=[('"', "double"), ("'", "single")],
                        default='"',
                        max_length=10,
                    ),
                ),
                ("last_modified", models.DateField(auto_now_add=True)),
                (
                    "columns",
                    models.ManyToManyField(
                        related_name="columns", to="schemes.SchemaColumn"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified"],
            },
        ),
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("file", models.FileField(upload_to="media/")),
                (
                    "schema",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schemes.schema",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
