# Generated by Django 3.1.1 on 2020-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemes", "0003_auto_20200910_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="last_modified",
            field=models.DateField(auto_now=True),
        ),
    ]
