FROM node:latest as build
WORKDIR .

ENV PATH /frontendapp/node_modules/.bin:$PATH

# install dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

# start app
# CMD ["npm", "start"]

RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build ./frontendapp/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]  