FROM python:3.8
WORKDIR /app

ENV PYTHONFAULTHANDLER=1 \
    PYTHONHASHSEED=random \
    PYTHONUNBUFFERED=1 \
    DJANGO_SETTINGS_MODULE=planeks.settings.dev

RUN pip install poetry 
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock
RUN poetry install --no-interaction
COPY . .

EXPOSE 8000

# ENTRYPOINT poetry run gunicorn -b :8000 planeks.wsgi --reload
# CMD ["poetry", "run", "gunicorn", "-b"< ":8000", "planeks.wsgi", "--reload"]
